djangousers/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djangousers.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

djangousers/www/common/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from . import views


urlpatterns = patterns('www.common.views',
    url(r'^page1/$', views.page1, name='page1'),
    url(r'^page2/$', views.page2, name='page2'),
    url(r'^page3/$', views.page3, name='page3'),
    url(r'^page4/$', views.page4, name='page4'),
    url(r'^page5/$', views.page5, name='page5'),
)

djangousers/www/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url, include
from django.contrib import admin


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', 'www.common.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^common/', include('www.common.urls', namespace='common')),
    url(r'^users/', include('www.users.urls', namespace='users')),
)

djangousers/www/users/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('www.users.views',
    url(r'^login/$', views.login_post, name='login'),
    url(r'^login_required/$', views.login_view, name='login_required'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^create_account/$', views.create_account, name='create_account'),
    url(r'^edit_account/$', views.edit_account, name='edit_account'),
    url(r'^change_password/$', views.change_password, name='change_password'),
)

djangousers/core/profiles/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth import models as auth_models
from django.utils.translation import ugettext_lazy as _


TITLE_CHOICES = (
    ('MR', _(u'Mr.')),
    ('MRS', _(u'Mrs.')),
    ('MS', _(u'Ms.')),
)


class UserProfile(auth_models.User):
    title = models.CharField(_(u'title'), max_length=3, choices=TITLE_CHOICES, blank=True)
    birthdate = models.DateField(_(u'birthdate'), blank=True)
    date_left = models.DateTimeField(_(u'date left'), blank=True)

    class Meta:
        verbose_name = _(u"user profile")
        verbose_name_plural = _(u"user profiles")

    def __unicode__(self):
        return self.user.username

djangousers/utils/models.py
# -*- coding: utf-8 -*-

djangousers/www/common/models.py
# -*- coding: utf-8 -*-

djangousers/www/users/models.py
# -*- coding: utf-8 -*-

djangousers/www/users/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth import models as auth_models


class UserForm(forms.ModelForm):

    class Meta:
        model = auth_models.User
        fields = ('username', 'first_name', 'last_name', 'email')

djangousers/www/common/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render

from djangousers.utils import mark_path

@mark_path
def home(request):
    return render(request, 'common/home.html')


@mark_path
def page1(request):
    return render(request, 'common/page1.html')


@mark_path
def page2(request):
    return render(request, 'common/page2.html')


@mark_path
def page3(request):
    return render(request, 'common/page3.html')


@mark_path
def page4(request):
    return render(request, 'common/page4.html')


@mark_path
@login_required(login_url=reverse_lazy('users:login_required'))
def page5(request):
    return render(request, 'common/page5.html')

djangousers/www/users/views.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _

from djangousers.utils import get_last_path

from . import forms


def login_post(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.info(request, _(u'Welcome back %s !') % user)
            else:
                messages.warning(request, _(u"Oops, this user is not active !"))
        else:
            messages.warning(request, _(u"Oops, unknown username or wrong password !"))
    return redirect(get_last_path(request))


def login_view(request):
    return render(request, 'users/login.html', {'autologin': 'true'})


def logout_view(request):
    logout(request)
    return redirect(get_last_path(request))


def create_account(request):
    if request.user.is_authenticated():
        messages.info(request, _(u'%s, you must be deconnected to create a new account' % request.user))
        return redirect('/')
    post = request.POST
    form = forms.UserForm(post or None)
    password_error = None
    if post:
        password = post.get('password')
        if len(password) < 4:
            password_error = _(u'Password must be at least 4 char long.')
        elif password != post.get('password2'):
            password_error = _(u'Passwords are different, please retype.')
        elif form.is_valid():
            form.save()
            username = post['username']
            password = post['password']
            user = form.instance
            if user:
                user.set_password(password)
                user.save()
                user = authenticate(username=username, password=password)
                login(request, user)
                messages.success(request, _(u'New user %s successfully created !') % user)
                return redirect(get_last_path(request))
            else:
                messages.warning(request, _(u'User creation problem, please retry.'))
    ctxt = {'form': form, 'password_error': password_error}
    return render(request, 'users/create_user.html', ctxt)


def edit_account(request):
    if not request.user.is_authenticated():
        messages.info(request, _(u'You must be connected to edit your account'))
        return redirect('/')
    user = request.user
    post = request.POST
    form = forms.UserForm(post or None, instance=user)
    if not settings.USERS_CAN_MODIFY_USERNAME:
        form.fields['username'].widget.attrs['readonly'] = True
    if not settings.USERS_CAN_MODIFY_EMAIL:
        form.fields['email'].widget.attrs['readonly'] = True
    if post and form.is_valid():
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.email = form.cleaned_data['email']
        try:
            user.save()
            messages.success(request, _(u'User %s successfully modified !') % user)
            return redirect(get_last_path(request))
        except Exception as e:
            messages.warning(request, _(u'User modification problem: %s' % e))
    return render(request, 'users/edit_user.html', {'form': form})


def change_password(request):
    user = request.user
    post = request.POST
    password_error = None
    if post:
        password = post.get('password')
        if len(password) < 4:
            password_error = _(u'Password must be at least 4 char long.')
        elif password != post.get('password2'):
            password_error = _(u'Passwords are different, please retype.')
        else:
            user.set_password(password)
            user.save()
            messages.success(request, _(u'Password successfully modified !'))
            return redirect(get_last_path(request))
    return render(request, 'users/change_password.html', {'password_error': password_error})

djangousers/www/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    {% block head_meta %}{% endblock %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <title>
        {% block head_title %}'Django Users'{% endblock %}
    </title>

    {% block head_css %}{% endblock %}
    {% block head_js %}{% endblock %}
    {% block head_inline_js %}{% endblock %}
</head>
<body>
<div id="all">
    {% block body_nav %}{% endblock %}
    {% block body_message %}{% endblock %}
    {% block body_header %}{% endblock %}
    {% block body_content %}{% endblock %}
    {% block body_footer %}{% endblock %}

    {% block body_login %}{% endblock %}
    {% block bottom_js %}{% endblock %}
</div>
</body>
</html>

djangousers/www/templates/common/home.html
{% extends "common_layout.html" %}
{% load i18n %}


{% block body_header %}
    <h1 style="text-align: center;">{% trans 'Welcome to Django User demo application' %}</h1>
{% endblock %}

djangousers/www/templates/common/page1.html
{% extends "common_layout.html" %}
{% load i18n %}


{% block body_header %}
    <h1 style="text-align: center;">{% trans 'This is page 1 of Django User demo application' %}</h1>
{% endblock %}

djangousers/www/templates/common/page2.html
{% extends "common_layout.html" %}
{% load i18n %}


{% block body_header %}
    <h1 style="text-align: center;">{% trans 'This is page 2 of Django User demo application' %}</h1>
{% endblock %}

djangousers/www/templates/common/page3.html
{% extends "common_layout.html" %}
{% load i18n %}


{% block body_header %}
    <h1 style="text-align: center;">{% trans 'This is page 3 of Django User demo application' %}</h1>
{% endblock %}

djangousers/www/templates/common/page4.html
{% extends "common_layout.html" %}
{% load i18n %}


{% block body_header %}
    <h1 style="text-align: center;">{% trans 'This is page 4 of Django User demo application' %}</h1>
{% endblock %}

djangousers/www/templates/common/page5.html
{% extends "common_layout.html" %}
{% load i18n %}


{% block body_header %}
    <h1 style="text-align: center;">{% trans 'This is page 5 of Django User demo application' %}</h1>
{% endblock %}

djangousers/www/templates/common_layout.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block head_meta %}
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
{% endblock %}

{% block head_css %}
<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block head_js %}
<script src="{% static 'js/jquery.tools.min.js' %}"></script>
{% endblock %}

{% block head_inline_js %}
<script>
var timeout     = 500;
var closetimer	= 0;
var dropdown    = [];
var ddmmenuitem = [];

function jsddm_open() {
    jsddm_canceltimer();
    jsddm_close();
    dropdown = $(this).children('ul').eq(0).css('visibility', 'visible');
    console.log(dropdown.length)
    if (dropdown.length)
        ddmmenuitem = $(this).find('a').eq(0).addClass('selected');
}

function jsddm_close() {
    if (dropdown.length) dropdown.css('visibility', 'hidden');
    dropdown = [];
    if (ddmmenuitem.length) ddmmenuitem.removeClass('selected');
}

function jsddm_timer() {
    closetimer = window.setTimeout(jsddm_close, timeout);
}

function jsddm_canceltimer() {
    if(closetimer) {
        window.clearTimeout(closetimer);
        closetimer = null;
    }}

$(function() {
    $('#jsddm > li').bind('mouseover', jsddm_open).bind('mouseout',  jsddm_timer);
});

document.onclick = jsddm_close;

$(function() {
    var modals = $("a[rel]").overlay({
        mask: {
            color: '#ebecff',
            loadSpeed: 200
        },
        closeOnClick: false,
        load: {{ autologin|default:0 }}
    });
    $("#login form").submit(function(e) {
        modals.eq(0).overlay().close();
    });
    $(".alert").delay(5000).slideUp(400);
    $('.jsddm > li').bind('mouseover', jsddm_open);
    $('.jsddm > li').bind('mouseout',  jsddm_timer);
    document.onclick = jsddm_close;
});
</script>
{% endblock %}

{% block body_nav %}
<div id="site-header">
    <a href="{% url 'home' %}"><img src="{% static 'img/SmallBeetle.jpg' %}"><h1>Scarabée</h1></a>
    <ul id="jsddm">
        <li class="home"><a href="{% url 'home' %}" {% if request.path|length < 2 %}class="active"{% endif %}>Home</a></li>
        <li><a href="{% url 'common:page1' %}" {% if 'page1' in request.path %}class="active"{% endif %}>Page 1</a></li>
        <li><a href="{% url 'common:page2' %}" {% if 'page2' in request.path %}class="active"{% endif %}>Page 2</a></li>
        <li><a href="{% url 'common:page3' %}" {% if 'page3' in request.path %}class="active"{% endif %}>Page 3</a></li>
        <li><a href="{% url 'common:page4' %}" {% if 'page4' in request.path %}class="active"{% endif %}>Page 4</a></li>
        <li><a href="{% url 'common:page5' %}" {% if 'page5' in request.path %}class="active"{% endif %}>Page 5</a></li>
        {% if user.is_authenticated %}
        <li class="right"><a href="#" style="text-transform: capitalize;">{% trans 'Welcome' %}&nbsp;{% firstof user.first_name user.username %}</a>
        <ul>
            <li><a href="{% url 'users:logout' %}">{% trans 'Logout' %}</a></li>
            <li><a href="{% url 'users:edit_account' %}">{% trans 'Edit User infos' %}</a></li>
            <li><a href="{% url 'users:change_password' %}">{% trans 'Change Password' %}</a></li>
        </ul>
        </li>
        {% else %}
        <li class="right"><a rel="#login" href="#">{% trans 'Login' %}</a></li>
        {% endif %}
    </ul>
</div>
<div class="clear"></div>
{% endblock %}

{% block body_login %}
<div class="modal" id="login">
    <h2>{% trans 'Login' %}</h2>
    <p>{% trans 'Please enter your credentials.' %}</p>
    {% include 'users/login_form.html' %}
</div>
{% endblock %}

{% block body_message %}
    {% include 'messages.html' %}
{% endblock %}

djangousers/www/templates/messages.html
<div>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message|safe }}</div>
    {% endfor %}
{% endif %}
</div>

djangousers/www/templates/users/change_password.html
{% extends "common_layout.html" %}
{% load i18n %}

{% block body_header %}
<h3 style="text-align: center; margin-top: 40px">{% trans 'Please enter your new password' %}</h3>
{% endblock %}

{% block body_content %}
<div class="well">
    <form action="#" method="post" autocomplete="off">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label">{% trans 'New password' %}*:</td>
                <td class="input"><input id="password" name="password" type="password" placeholder="{% trans 'new password' %}"/></td>
                <td class="error">{% if password_error %}<ul class="errorlist"><li>{{ password_error }}</li></ul>{% endif %}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'New password again' %}*:</td>
                <td class="input"><input id="password2" name="password2" type="password" placeholder="{% trans 'new password again' %}"/></td>
            </tr>
        </table>
        <p class="actions">
            <button type="submit">{% trans 'Submit' %}</button>
            <button type="button" onclick="window.location.href='{{ LAST_TRUE_PAGE }}';">{% trans 'Cancel' %}</button>
        </p>
    </form>
</div>
{% endblock %}

djangousers/www/templates/users/create_user.html
{% extends "common_layout.html" %}
{% load i18n %}

{% block body_header %}
<h3 style="text-align: center; margin-top: 40px">{% trans 'Please enter your informations' %}</h3>
{% endblock %}

{% block body_content %}
<div class="well">
    <form action="#" method="post" autocomplete="off">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label">{% trans 'Username' %}*:</td>
                <td class="input">{{ form.username }}</td>
                <td class="error">{{ form.errors.username }}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'First name' %}:</td>
                <td class="input">{{ form.first_name }}</td>
                <td class="error">{{ form.errors.first_name }}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'Last name' %}:</td>
                <td class="input">{{ form.last_name }}</td>
                <td class="error">{{ form.errors.last_name }}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'Email' %}*:</td>
                <td class="input">{{ form.email }}</td>
                <td class="error">{{ form.errors.email }}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'Password' %}*:</td>
                <td class="input"><input id="password" name="password" type="password" placeholder="{% trans 'password' %}"/></td>
                <td class="error"><ul class="errorlist"><li>{{ password_error }}</li></ul></td>
            </tr>
            <tr>
                <td class="label">{% trans 'Password again' %}*:</td>
                <td class="input"><input id="password2" name="password2" type="password" placeholder="{% trans 'password again' %}"/></td>
            </tr>
        </table>
        <p class="actions">
            <button type="submit">{% trans 'Submit' %}</button>
            <button type="button" onclick="window.location.href='{{ LAST_TRUE_PAGE }}';">{% trans 'Cancel' %}</button>
        </p>
    </form>
</div>
{% endblock %}

djangousers/www/templates/users/edit_user.html
{% extends "common_layout.html" %}
{% load i18n %}

{% block body_header %}
<h3 style="text-align: center; margin-top: 40px">{% trans 'Please edit your informations' %}</h3>
{% endblock %}

{% block body_content %}
<div class="well">
    <form action="#" method="post" autocomplete="off">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label">{% trans 'Username' %}*:</td>
                <td class="input">{{ form.username }}</td>
                <td>{{ form.errors.username }}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'First name' %}:</td>
                <td class="input">{{ form.first_name }}</td>
                <td>{{ form.errors.first_name }}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'Last name' %}:</td>
                <td class="input">{{ form.last_name }}</td>
                <td>{{ form.errors.last_name }}</td>
            </tr>
            <tr>
                <td class="label">{% trans 'Email' %}*:</td>
                <td class="input">{{ form.email }}</td>
                <td>{{ form.errors.email }}</td>
            </tr>
        </table>
        <p class="actions">
            <button type="submit">{% trans 'Submit' %}</button>
            <button type="button" onclick="window.location.href='{{ LAST_TRUE_PAGE }}';">{% trans 'Cancel' %}</button>
        </p>
    </form>
</div>
{% endblock %}

djangousers/www/templates/users/login.html
{% extends "common_layout.html" %}
{% load i18n %}

{% block body_login %}
<div class="modal" id="login">
    <h2>{% trans 'Login Required' %}</h2>
    <p>{% trans 'This page has restricted access rights.' %}</p>
    <p>{% trans 'Please enter your credentials.' %}</p>
    {% include 'messages.html' %}
    {% include 'users/login_form.html' %}
</div>
{% endblock %}

{% block body_message %}
{% endblock %}

djangousers/www/templates/users/login_form.html
{% load i18n utils %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td class="label">{% trans 'Username' %}:</td>
            <td><input id="username" name="username" type="text" placeholder="{% trans 'username' %}"/></td>
        </tr>
        <tr>
            <td class="label">{% trans 'Password' %}:</td>
            <td><input id="password" name="password" type="password" placeholder="{% trans 'password' %}"/></td>
        </tr>
    </table>
    <p class="actions">
        <button type="submit">{% trans 'Login' %}</button>
        <button type="button" class="close">{% trans 'Cancel' %}</button>
        {% if USERS_CAN_CREATE_USER %}
        <a href="{% url 'users:create_account' %}">{% trans 'Click here to create an account' %}</a>
        {% endif %}
    </p>
</form>